name: Terraform Multi-Cloud with Approval
 
on:
  push:
    branches: [ main ]
 
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
 
    # AWS Login
    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
 
    # Azure Login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
 
    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Plan
      run: terraform plan -out=tfplan
 
 
  terraform-apply:
    name: Terraform Apply (Manual Approval)
    needs: terraform-plan
    runs-on: ubuntu-latest
 
    environment:
      name: production   # 👈 this triggers manual approval
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
 
    # AWS Login
    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
 
    # Azure Login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
 
    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
